@startuml context_diagram

!include ../templates/C4_Context.puml

title Диаграмма контекста - Цифровизация депозитов и кредитов (v2)

Person(client, "Клиент", "Пользователь цифровых услуг банка")
Person(manager, "Сотрудник банка", "Сотрудник кредитного/депозитного отделов банка")
Person(CallManager, "Менеджер кол-центра", "Менеджер кол-центра по оформлению заявок клиентов")
Person(PartnerCallManager, "Менеджер партнерского КЦ", "Менеджер партнерского кол-центра")

System(site, "Сайт банка", "Веб-сайт для новых клиентов с базовой информацией о продуктах")
System(InternetBank, "Интернет-банк", "Личный кабинет для существующих клиентов с полным функционалом")
System(abc, "АБС банка", "Автоматизированная банковская система - ядро банковских операций")
System(CallCenter, "Система колл-центра", "CRM система для обработки входящих заявок")
System_Ext(PartnerCallCenter, "Партнерский кол-центр", "Внешняя система обработки заявок")
System(SMSGateway, "СМС-шлюз", "Сервис отправки SMS-сообщений клиентам")
System_Ext(SMSService, "Сервис рассылки уведомлений", "Отправляет СМС пользователям")
System_Ext(KreditHistorySystem, "Бюро кредитных историй")
System(ScoringSystem, "Система скоринга", "Получает информацию о заявке и передает оценку")
System(SFTPServer, "SFTP-сервер", "Сервер для безопасного обмена файлами с партнерами")

SystemQueue(broker, "Kafka", "Асинхронный обмен сообщениями")

' Связи клиента
Rel(client, site, "Просматривает предложения, проходит регистрацию, подает заявку")
Rel(client, InternetBank, "Просматривает информацию по личному кабинету и подает заявку")
Rel(SMSService, client, "Доставляет уведомления клиенту")

' Связи кол-центра
Rel(site, broker, "Передает заявку с сайта")
Rel(CallManager, CallCenter, "Обрабатывает заявку и связывается с клиентом для оформления")
Rel(CallCenter, broker, "Получает первичные заявки и передает актуальные сведения о заявке и клиенте")

' Связи АБС
Rel(manager, abc, "Обрабатывает заявку")
Rel(abc, SMSGateway, "Отправляет уведомления")
Rel(abc, KreditHistorySystem, "Получает информацию о кредитной истории")

' Связи интернет-банка
Rel(InternetBank, broker, "Передает заявки, получает актуальную информацию о ставках, предложениях, решениях")

Rel(SMSGateway, SMSService, "Передает уведомления для отправки")
Rel(ScoringSystem, broker, "Получение информации о новых заявках и передача оценки")
Rel(abc, broker, "Передает актуальную информацию о продуктах и заявках")

' Добавление предложений
Rel(PartnerCallManager, PartnerCallCenter, "Обрабатывает заявку и консультирует клиента")
Rel(PartnerCallCenter, SFTPServer, "Получает файлы с актуальными ставками", "SFTP")
Rel(abc, SFTPServer, "Публикует файлы с актуальными ставками", "SFTP")

@enduml