@startuml

!include ../templates/C4_Context.puml

Person(client, "Клиент", "Подаёт заявки на кредит через сайт или интернет-банк")
Person(manager, "Сотрудник отделения", "Продолжает/оформляет заявки в отделении")
Person(operator, "Сотрудник кол-центра", "Консультация клиента по вопросам кредитования")

System(site, "Сайт", "Витрина кредитов, подача онлайн-заявки")
System(ib, "Интернет-банк", "Подача заявки и предодобренные предложения")
System(abc, "АБС", "Оформление кредитов, учёт и проводки")
System(conveyor, "Кредитный конвейер", "Обработка заявок 24/7, BPM (Camunda)")
System(ScoringSystem, "Система кредитного скоринга", "Рассчёт скорингового балла")
System(sms, "СМС-шлюз", "Отправка уведомлений клиентам")
System(CallSystem, "Система кол-центра", "Принимает и формирует заявки")
System(CreditService, "Система кредитования", "Управляет кредитами")

System_Ext(bki, "Бюро кредитных историй", "Внешняя система, API для проверки кредитной истории")
System_Ext(SMSService, "Телеком-оператор", "Отправляет СМС пользователям")

Rel(client, site, "Просмотр условий, подача заявки")
Rel(client, ib, "Просмотр условий/офферов, подача заявки")
Rel(ScoringSystem, bki, "Запрос кредитной истории")

Rel(manager, CreditService, "Передача оформленной заявки")

Rel(site, CreditService, "Передача онлайн-заявки")
Rel(ib, CreditService, "Передача онлайн-заявки / предодобренной")
Rel(CallSystem, CreditService, "Передача заявки")

' Связи сервиса кредитования
Rel(CreditService, ScoringSystem, "Получает информацию об оценке пользователя")
Rel(CreditService, abc, "Передает подготовленные заявки")
Rel(CreditService, conveyor, "Получает результат процесса обработки заявок на кредит")

Rel(sms, SMSService, "Отправляемые СМС-сообщения")

Rel(operator, CallSystem, "Обрабатывает заявки клиентов")

Rel(abc, sms, "Уведомления о решении по кредиту")
Rel(SMSService, client, "Уведомления о решении по кредиту")
@enduml
